=== aimozg/Corruption-of-Champions-Mod/content/story.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
    <!-- default namespace = "xxc-story" -->
    <!-- core xlogic -->
    <xs:group name="content">
        <xs:sequence>
            <xs:choice minOccurs="0">
                <xs:element ref="b"/>
                <xs:element ref="i"/>
                <xs:element ref="font"/>
                <xs:element ref="if"/>
                <xs:element ref="switch"/>
                <xs:element ref="xcc-content"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>
    <xs:element name="if">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
                <xs:group minOccurs="0" maxOccurs="unbounded" ref="elseif"/>
                <xs:group minOccurs="0" ref="else"/>
            </xs:sequence>
            <xs:attribute name="test" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="if-big">
        <xs:sequence>
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="elseif"/>
            <xs:group minOccurs="0" ref="else"/>
        </xs:sequence>
    </xs:group>
    <xs:attributeGroup name="if-short">
        <xs:attribute name="then" use="required"/>
        <xs:attribute name="else"/>
    </xs:attributeGroup>
    <xs:group name="elseif">
        <xs:sequence>
            <xs:element ref="elseif"/>
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        </xs:sequence>
    </xs:group>
    <xs:element name="elseif">
        <xs:complexType>
            <xs:attribute name="test" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="else">
        <xs:sequence>
            <xs:element ref="else"/>
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        </xs:sequence>
    </xs:group>
    <xs:element name="else">
        <xs:complexType/>
    </xs:element>
    <xs:element name="switch">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="case"/>
                <xs:element minOccurs="0" ref="default"/>
            </xs:sequence>
            <xs:attribute name="value"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="case">
        <xs:complexType mixed="true">
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
            <xs:attribute name="test"/>
            <xs:attribute name="value"/>
            <xs:attribute name="values"/>
            <xs:attribute name="lt"/>
            <xs:attribute name="gt"/>
            <xs:attribute name="ne"/>
            <xs:attribute name="lte"/>
            <xs:attribute name="gte"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="default">
        <xs:complexType mixed="true">
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        </xs:complexType>
    </xs:element>
    <!-- xxc statements -->
    <xs:element name="b">
        <xs:complexType mixed="true">
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="i">
        <xs:complexType mixed="true">
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="font">
        <xs:complexType mixed="true">
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
            <xs:attribute name="color"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="xcc-named-content" abstract="true" substitutionGroup="xcc-content"/>
    <xs:element name="xcc-content" abstract="true"/>
    <xs:element name="t" substitutionGroup="xcc-content" type="xs:string"/>
    <xs:complexType name="namedBlock" mixed="true">
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        <xs:attribute name="name"/>
    </xs:complexType>
    <xs:element name="text" substitutionGroup="xcc-named-content" type="namedBlock"/>
    <xs:element name="string" substitutionGroup="xcc-named-content" type="namedBlock"/>
    <xs:element name="lib" substitutionGroup="xcc-named-content">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="xcc-named-content"/>
            </xs:sequence>
            <xs:attribute name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="scene" substitutionGroup="xcc-named-content">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="namedBlock">
                    <xs:attribute ref="xsi:noNamespaceSchemaLocation"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro" substitutionGroup="xcc-named-content" type="namedBlock"/>
    <xs:element name="set" substitutionGroup="xcc-content">
        <xs:complexType mixed="true">
            <xs:attribute name="var" use="required"/>
            <xs:attribute name="value"/>
            <xs:attribute name="op">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="append"/>
                        <xs:enumeration value="set"/>
                        <xs:enumeration value="add"/>
                        <xs:enumeration value="+="/>
                        <xs:enumeration value="="/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="extend-story" substitutionGroup="xcc-named-content" type="namedBlock"/>
    <xs:element name="display" substitutionGroup="xcc-content">
        <xs:complexType>
            <xs:attribute name="ref" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="command" substitutionGroup="xcc-content" type="xs:string"/>
    <xs:element name="output" substitutionGroup="xcc-content" type="xs:string"/>
    <xs:element name="include" substitutionGroup="xcc-content">
        <xs:complexType>
            <xs:attribute name="path" use="required"/>
            <xs:attribute name="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="true"/>
                        <xs:enumeration value="false"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <!-- mod content -->
    <xs:element name="mod-content" abstract="true" substitutionGroup="xcc-named-content"/>
    <!-- | mod-armor | fork-armor -->
    <xs:element name="armor" substitutionGroup="mod-content">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="short"/>
                <xs:element ref="name"/>
                <xs:element ref="long"/>
                <xs:element ref="description"/>
                <xs:element ref="value"/>
                <xs:element ref="defense"/>
                <xs:element ref="subType"/>
                <xs:element ref="supportsUndergarment"/>
                <xs:element ref="perk"/>
                <xs:element ref="onEquip"/>
            </xs:choice>
            <xs:attribute name="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="short" type="xs:string"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="long" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>
    <xs:element name="defense" type="xs:string"/>
    <xs:element name="subType" type="xs:string"/>
    <xs:element name="supportsUndergarment">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:enumeration value="true"/>
                <xs:enumeration value="false"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="perk">
        <xs:complexType>
            <xs:all>
                <xs:element minOccurs="0" ref="value1"/>
                <xs:element minOccurs="0" ref="value2"/>
                <xs:element minOccurs="0" ref="value3"/>
                <xs:element minOccurs="0" ref="value4"/>
            </xs:all>
            <xs:attribute name="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="value1" type="xs:string"/>
    <xs:element name="value2" type="xs:string"/>
    <xs:element name="value3" type="xs:string"/>
    <xs:element name="value4" type="xs:string"/>
    <xs:element name="onEquip">
        <xs:complexType mixed="true">
            <xs:group minOccurs="0" maxOccurs="unbounded" ref="content"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="reflist" substitutionGroup="mod-content">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ref"/>
            </xs:sequence>
            <xs:attribute name="id" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="any"/>
                        <xs:enumeration value="ItemType"/>
                        <xs:enumeration value="PerkType"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="ref">
        <xs:complexType>
            <xs:attribute name="id" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aimozg/Corruption-of-Champions-Mod/content/coc.xml
<?xml version="1.0" encoding="utf-8"?>
<extend-story name="/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="story.xsd">
    <!--Areas-->
    <include path="coc/desert.xml"/>
    <include path="coc/forest.xml"/>
    <include path="coc/mountain.xml"/>
    <extend-story name="deepwoods">
        <lib name="strings">
            <text name="walk">
                You enjoy a peaceful walk in the deepwoods.  It gives you time to think over the recent, disturbing events.
                <command>BuffOrRecover('tou',5,'deepwoods/walk','Deepwoods walk',36,2)</command>
                <command>BuffOrRecover('int',10,'deepwoods/walk','Deepwoods walk',36,2)</command>
            </text>
        </lib>
    </extend-story>

    <!-- Monsters -->
    <include path="coc/monsters/goblin.xml"/>

    <!-- NPCs -->
    <include path="coc/NPC/celess.xml"/>
    <include path="coc/NPC/samirah.xml"/>
    <!--<include path="coc/NPC/diva.xml"/>-->
    <include path="coc/NPC/teladreshops.xml"/>

    <!--Other-->
    <include path="coc/appearance.xml"/>

    <!--Items-->
    <armor id="AdvClth">
        <short>G. Clothes</short>
        <name>green adventurer's clothes</name>
        <long>a green adventurer's outfit, complete with pointed cap</long>
        <defense>2</defense>
        <value>50</value>
        <description>A set of comfortable green adventurer's clothes.  It even comes complete with a pointy hat!</description>
        <subType>Light</subType>
    </armor>
    <armor id="A.Robe">
        <short>A.Robe</short>
        <name>apprentice's robe</name>
        <long>an apprentice's robe</long>
        <defense>1</defense>
        <value>25</value>
        <description>This drab robe lacks adornment, yet retains an air of mysticality. The low quality of the fabric coupled with its mystic air suggests that it is a garment meant for mages in training.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>10</value1>
        </perk>
    </armor>
    <armor id="ArcaBangl">
        <short>ArcaneBangles</short>
        <name>arcane bangles</name>
        <long>a set of arcane bangles</long>
        <defense>1</defense>
        <value>150</value>
        <description>Silver bangles to be worn from the wrists and ankles, inscribed with arcane runes.  For some reason, you feel like wearing these with armor or clothes is somehow wrong.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>20</value1>
        </perk>
        <perk id="Slutty Seduction">
            <value1>5</value1>
        </perk>
    </armor>
    <armor id="B.Dress">
        <short>Long Dress</short>
        <name>long ballroom dress patterned with sequins</name>
        <long>a ballroom dress patterned with sequins</long>
        <defense>0</defense>
        <value>40</value>
        <description>A long ballroom dress patterned with sequins.  Perfect for important occasions.</description>
        <subType>Medium</subType>
    </armor>
    <armor id="BimboSk">
        <short>BimboSk</short>
        <name>bimbo skirt</name>
        <long>a skirt that looks like it belongs on a bimbo</long>
        <defense>1</defense>
        <value>40</value>
        <description>A tight, cleavage-inducing halter top and an extremely short miniskirt.  The sexual allure of this item is undoubtable.</description>
        <subType>Light</subType>
        <supportsUndergarment>false</supportsUndergarment>
        <perk id="Slutty Seduction">
            <value1>10</value1>
        </perk>
    </armor>
    <armor id="B.Kimono">
        <short>B.Kimono</short>
        <name>blue kimono</name>
        <long>a blue kimono</long>
        <defense>1</defense>
        <value>200</value>
        <description>This lovely blue kimono is adorned with a floral pattern. It will likely increase your spiritual power as a kitsune.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>20</value1>
        </perk>
        <perk id="Seer’s Insight">
            <value1>0.2</value1>
        </perk>
    </armor>
    <armor id="BonStrp">
        <short>BonStrp</short>
        <name>barely-decent bondage straps</name>
        <long>a set of bondage straps</long>
        <defense>0</defense>
        <value>40</value>
        <description>These leather straps and well-placed hooks are actually designed in such a way as to be worn as clothing.  While they technically would cover your naughty bits, virtually every other inch of your body would be exposed.</description>
        <subType>Light</subType>
        <supportsUndergarment>false</supportsUndergarment>
        <perk id="Slutty Seduction">
            <value1>10</value1>
        </perk>
    </armor>
    <armor id="C.Cloth">
        <short>C.Cloth</short>
        <name>comfortable clothes</name>
        <long>a set of comfortable clothes</long>
        <defense>0</defense>
        <value>1</value>
        <description>These loose fitting and comfortable clothes allow you to move freely while protecting you from the elements.</description>
        <subType>Light</subType>
    </armor>
    <armor id="ChBikni">
        <short>Chn Bikini</short>
        <name>revealing chainmail bikini</name>
        <long>a chainmail bikini</long>
        <defense>2</defense>
        <value>80</value>
        <description>A revealing chainmail bikini that barely covers anything.  The bottom half is little more than a triangle of metal and a leather thong.</description>
        <subType>Light</subType>
        <supportsUndergarment>false</supportsUndergarment>
        <perk id="Slutty Seduction">
            <value1>5</value1>
        </perk>
    </armor>
    <armor id="ClssyCl">
        <short>Suitclothes</short>
        <name>classy suitclothes</name>
        <long>a set of classy suit-clothes</long>
        <defense>1</defense>
        <value>40</value>
        <description>A set of classy suitclothes.</description>
        <subType>Light</subType>
    </armor>
    <armor id="DSclArm">
        <short>D.Scale Armor</short>
        <name>dragonscale armor</name>
        <long>a suit of dragonscale armor</long>
        <defense>20</defense>
        <value>800</value>
        <description>This armor is cleverly fashioned from dragon scales. It offers high protection while at the same time, quite flexible.</description>
        <subType>Medium</subType>
    </armor>
    <armor id="DSclRob">
        <short>D.Scale Robes</short>
        <name>dragonscale robes</name>
        <long>a dragonscale robes</long>
        <defense>10</defense>
        <value>500</value>
        <description>This robe is expertly made from dragon scales. It offers high protection while being lightweight and should be comfortable to wear all day.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>20</value1>
        </perk>
    </armor>
    <armor id="EH.Garb">
        <short>E.Heretic‘s Garb</short>
        <name>Ebonweave Heretic‘s Garb</name>
        <long>an Ebonweave Heretic‘s Garb</long>
        <defense>20</defense>
        <value>1600</value>
        <description>This outfit is ebonweave, created using refined ebonbloom petals. The outfit consists of arrowproof clothes, covered by a mesh breastplate and leatherlike duster inscribed with glyphs of magic and warding.  A trilby adorned with a moon pin completes the look.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>20</value1>
        </perk>
        <perk id="Seer’s Insight">
            <value1>0.2</value1>
        </perk>
    </armor>
    <armor id="EWJack">
        <short>E.W. Jacket</short>
        <name>ebonweave jacket</name>
        <long>an ebonweave jacket</long>
        <defense>24</defense>
        <value>960</value>
        <description>This outfit is ebonweave, created using refined ebonbloom petals. The outfit consists of a leatherlike jacket, a mesh breastplate and a set of arrowproof clothing. Between them all, the outfit provide layers of protection rivaling heavier, more traditional armor.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>15</value1>
        </perk>
    </armor>
    <armor id="EWPltMa">
        <short>E.W. Platemail</short>
        <name>ebonweave platemail</name>
        <long>an ebonweave platemail</long>
        <defense>36</defense>
        <value>4320</value>
        <description>The armor is ebonweave, created using refined ebonbloom petals. The armor consists of two layers, an outer layer of ebonweave playing, and an inner layer of arrowproof ebonweave cloth.</description>
        <subType>Heavy</subType>
        <perk id="Wizard's Endurance">
            <value1>15</value1>
        </perk>
    </armor>
    <armor id="EWRobe">
        <short>E.W. Robe</short>
        <name>ebonweave robe</name>
        <long>an ebonweave robe</long>
        <defense>12</defense>
        <value>600</value>
        <description>This robe is ebonweave, created using refined ebonbloom petals. This robe is as comfortable as cloth yet more protective than chainmail. The cloth has a mystic aura, helpful when working magic.</description>
        <subType>Light</subType>
        <perk id="Wizard's Endurance">
            <value1>30</value1>
        </perk>
    </armor>
    <armor id="FullChn">
        <short>Full Chain</short>
        <name>full-body chainmail</name>
        <long>a full suit of chainmail armor</long>
        <defense>8</defense>
        <value>320</value>
        <description>This full suit of chainmail armor covers its wearer from head to toe in protective steel rings.</description>
        <subType>Medium</subType>
    </armor>
    <armor id="FullPlt">
        <short>Full Plate</short>
        <name>full platemail</name>
